### ISSUE TITLE
Memory cache vs hardware bitmap

### ISSUE THREAD

**Issue by Khang-NT** [coil-kt/coil#1017]
**Describe the bug**
`coil` should take `Bitmap.Config` into account when checking memory cache. In some case, using the wrong bitmap config lead to crash, so it's very important.

**To Reproduce**
```kotlin
val res1 = imageLoader.execute(ImageRequest.Builder(appContext)
    .data(data)
    .bitmapConfig(Bitmap.Config.HARDWARE)
    .build()).drawable
            
val res2 = imageLoader.execute(ImageRequest.Builder(appContext)
    .data(data)
    .bitmapConfig(Bitmap.Config.ARGB_8888)
    .build()).drawable

expect((res1 as BitmapDrawable).bitmap !== (res2 as BitmapDrawable).bitmap)
```

**Comment by Khang-NT** [comment]
In my case, I can reuse cached `ARGB_8888` bitmap to fill the request `HARDWARE` bitmap, but not vise versa.

**Comment by colinrtwhite** [comment]
Setting `bitmapConfig` on an `ImageRequest` isn't guaranteed since we can't guarantee it for certain decoders unfortunately (e.g. `MediaMetadataDecoder`). For your case you want to use `allowHardware(false)`. That will prevent the request from returning a hardware bitmap; [the memory cache takes it into account as well](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/memory/MemoryCacheService.kt#L92).
