### ISSUE TITLE
bitmap

### ISSUE THREAD

**Issue by mt131** [coil-kt/coil#102]
with coil i can load drawable like that
Coil.load(context, url) {
    target { drawable ->
        // Handle the successful result.
    }
}
how to load with bitmap?

**Comment by timbrueggenthies** [comment]
Maybe you could adjust the request a bit to improve the ability to follow the problem. 
Helps the maintainers to understand how they can help.

**Comment by VMadalin** [comment]
@mt131 Correct me please in case I'm wrong. You want to obtain the `bitmap` object when successful downloaded the image from url. This maybe isn't the most expected behaviour on use this library but knowing that:

>  A Drawable is an abstraction of "something that can be drawn". It could be a Bitmap (wrapped up as a BitmapDrawable), but it could also be a solid color, a collection of other Drawable objects, or any number of other structures. 

You can obtain easy your bitmap and use it for your proposes. Here I share with you a snipped of code for do that: https://stackoverflow.com/a/10600736/11009254

**Comment by mt131** [comment]
> @mt131 Correct me please in case I'm wrong. You want to obtain the `bitmap` object when successful downloaded the image from url. This maybe isn't the most expected behaviour on use this library but knowing that:
> 
> > A Drawable is an abstraction of "something that can be drawn". It could be a Bitmap (wrapped up as a BitmapDrawable), but it could also be a solid color, a collection of other Drawable objects, or any number of other structures.
> 
> You can obtain easy your bitmap and use it for your proposes. Here I share with you a snipped of code for do that: https://stackoverflow.com/a/10600736/11009254

thanks
