### ISSUE TITLE
Resizing for cached images does not work

### ISSUE THREAD

**Issue by aaajiekc** [coil-kt/coil#105]
**Describe the bug**
I have the same image loaded twice but with different size parameters. In both cases, a cache is enabled.
The larger image comes in onSuccess callback despite the size method.

**To Reproduce**
Get an image from the cache and try resizing it using size method.

**Expected behavior**
Image of the correct size according to the parameters passed to the size method

**Logs/Screenshots**
![image](https://user-images.githubusercontent.com/11936619/65123107-c5900400-da1c-11e9-894d-e5ce129c5c9b.png)

**Library version**
0.7.0

**Comment by colinrtwhite** [comment]
This is currently intended behaviour. Coil is pretty permissive about reusing drawables and will reuse drawables that are at least the size of the requested dimensions. In this case since the cached drawable is larger than the requested dimensions, it will be returned.

I understand there might be cases where users need the dimensions to be exact (or as exact as possible). I'm tracking support for that on this ticket: #76.
