### ISSUE TITLE
Image not load from unsecure link

### ISSUE THREAD

**Issue by rohitjakhar** [coil-kt/coil#1063]
I am trying to load an image from not-secure link (not have SSL certificate) and it failed to load it and load error image.
Is there any way to load image from not-secure link ?

**Comment by yschimke** [comment]
Noticed this while passing, so adding a non-authoritative answer...

I assume OkHttp is the only place this will stop you.

If you know of a specific host then you can allowlist that.

```
  val clientCertificates = HandshakeCertificates.Builder()
      .addPlatformTrustedCertificates()
      .addInsecureHost(server.hostName)
      .build()

  val client = OkHttpClient.Builder()
      .sslSocketFactory(clientCertificates.sslSocketFactory(), clientCertificates.trustManager)
      .build()
```      

Otherwise there are lots of tutorials for how to disable security https://futurestud.io/tutorials/retrofit-2-how-to-trust-unsafe-ssl-certificates-self-signed-expired

Then configure a custom okhttp - https://coil-kt.github.io/coil/recipes/#using-a-custom-okhttpclient

**Comment by colinrtwhite** [comment]
I think @yschimke is right - you may also have to set up a [network security config](https://developer.android.com/training/articles/security-config). Also please ask questions in Github Discussions.
