### ISSUE TITLE
Images not displayed in Android emulator

### ISSUE THREAD

**Issue by lukaszkalnik** [coil-kt/coil#1126]
Using `AsyncImage` images are not displayed in Android emulator.
The only way to show them is to add the following line to the AndroidManifest:
```
android:usesCleartextTraffic="true"
```
then the images show normally. 
On a real Android device the images are shown without setting `usesCleartextTraffic`. Also the images can be opened by Chrome on the emulator.

Example link:
```
https://image.tmdb.org/t/p/w780/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg
```
coil-compose 2.0.0-alpha06

**Comment by colinrtwhite** [comment]
I don't think this is an issue with Coil since Coil's networking is handled by OkHttp which relies on the device's security provider. It sounds like the emulator's security provider isn't the same as the one on your device, which is why it's failing to trust your server. I'd try [adding the Conscrypt security provider](https://github.com/square/okhttp#requirements) instead of using the device's provider.

**Comment by lukaszkalnik** [comment]
Thank you again for a helpful explanation!

**Comment by lukaszkalnik** [comment]
Update: it's actually the fact that Android emulator seems to not synchronize date and time with the network. After setting the time/date manually to the current one, downloading images started working.

Also cold booting the emulator might help (looks like booting from a saved image for some reason sets the date/time to the one from when the image was saved).
