### ISSUE TITLE
DiskCache should work like MemoryCache

### ISSUE THREAD

**Issue by gergely-sallai** [coil-kt/coil#113]
**Is your feature request related to a problem? Please describe.**
It seems that DiskCache feature caches the downloaded image only, so every transformation needs to be calculated again if the image is loaded from DiskCache.

This is problematic for two reasons:
- Memory and Disk Cache behave differently: Memory cache seem to cache the end result after all transformations are applied. Which is the correct way of caching in my opinion.
- If an image loading is more transformation heavy (i.e lots of compute intensive transformations happening) caching on Disk does not help a whole lot because all the transformations need to be calculated on every Disk cache fetch.

It would make sense to cache the resulting image on Disk and reuse later.

**Describe the solution you'd like**
I expect both Memory and Disk Cache to work the same way: cache the resulting image after the transformations are applied and be able to use the already existing `key` feature to name and refer to cached images.

**Additional context**
I understand that this would probably remove the possibility to use OkHttp's disk cache feature unfortunately.

*Awesome library BTW, I love it! Keep up the good work!*

**Comment by colinrtwhite** [comment]
Thanks for the enhancement request. Unfortunately, I'm not sure this is a good fit for Coil as adding support for this would require Coil to implement its own disk cache.

One of the main design decisions behind Coil was to rely on OkHttp's disk cache as:
1. This significantly reduces the complexity + size of Coil's codebase.
2. Coil automatically handles `Cache-Control` headers for free (something that Glide does not).

In addition, persisting transformations to the disk cache would require adding a version number to every `Transformation` cache key since those keys are now persisted on disk across library upgrades.

If you're performing a lot of transformations and want to cache them on disk, I'd recommend performing them ahead of time on the server instead. I know most people might not have access to the server serving the images, however it's significantly better to perform those transformations on the server where it's a much more powerful computer and they only need to be performed once (as opposed to on each user's device).

**Comment by NickM-27** [comment]
I kind of have the opposite opinion, if I have an image which has different slightly transformations in different places of the app, I don't want Coil to save each variation of that separately. Plus once the image is loaded from disk and saved with the transformations to the memory cache, it really only has an effect on the first load of an app instance.

**Comment by gergely-sallai** [comment]
I completely understand your reasoning behind the design decision that you don't want to implement your own disk cache. And persisting between lib and app updates where the transformations could change is problematic, I agree; I did not consider this one. What I considered was the memory and computational footprint of the app, but it might not worth the effort.

Although it is still confusing that Coil has two kind of caches and each of them cache at different places. This should be documented. Or better yet maybe have an interface for both kind of caches like `InputImageCache` and `TransformedImageCache` (two very badly named examples, I'm sure you could come up with more appropriately named ones :) ). This way if a library user would like could add her own caching mechanism at any point. What do you think?

**Comment by colinrtwhite** [comment]
@gergely-sallai Thanks for the enhancement request, but I don't think this is a good fit for Coil given the reasons [here](https://github.com/coil-kt/coil/issues/113#issuecomment-533842984).
