### ISSUE TITLE
XML Drawable Color Got Pale/Faded inside RecyclerView

### ISSUE THREAD

**Issue by wiryadev** [coil-kt/coil#1181]
**Describe the bug**
I wan to load a drawable vector asset (xml format) and give it color tint. But when i run the app, the tint color looks pale/faded, like the alpha is close to zero. I expect the color tint when runtime is the same with previews and not faded out. I try to use Glide and no library (with setImageResource) and both works perfectly fine, no pale tint color. I dont know if this was intended behavior for Coil but i think this is an issue.

**To Reproduce**
Here is small projects which include comparison between the three: [CoilDrawableRepro](https://github.com/wiryadev/CoilDrawableRepro).

**Logs/Screenshots**
<img src="https://user-images.githubusercontent.com/26060382/156728419-7f4c06c6-983d-43f5-a959-0730405f0326.png" width="360" />

**Version**
Both Coil 2.0.0-rc01 and 1.4.0 has this issue based on my trial

**Notes**
- This only happens when using drawable XML files, when i test it against JPG/PNG file, the issue is non exist.
- I dont use custom/create my own ImageLoader, i only use the existing `load()` function

Thanks in advance.

**Comment by colinrtwhite** [comment]
@wiryadev This is because your XML drawable sets `android:tint="?attr/colorControlNormal"`. Coil pre-converts vector drawables to bitmaps on a background thread, which bakes that tint into the drawable then a custom tint is applied by the `ImageView` afterwards. Removing `android:tint="?attr/colorControlNormal"` fixes the issue.
