### ISSUE TITLE
Support loading animated svg from a URL

### ISSUE THREAD

**Issue by mike14u** [coil-kt/coil#1405]
**Is your feature request related to a problem? Please describe.**
Right now coil is able to support loading static svg files from url, but for animated svg, its just not animating

**Describe the solution you'd like**
A straightforward support to animated svg parsing and loading from url

**Additional context**
n/a

**Comment by colinrtwhite** [comment]
Duplicate: https://github.com/coil-kt/coil/issues/1334

**Comment by mike14u** [comment]
I understand this is a duplicate but closing/completing this issue? It's not even in the coil library yet... This explains why coil has less issues lol. Anyway I came unto the root issue request here https://github.com/BigBadaboom/androidsvg/issues/87 

Last comment was 2018 and I'm sure no one is working on this enhancement. If I may suggest you can create the decoders internally (inside coil-kt library) instead of relying to androidsvg (latest release was 2019 according to Github). Thanks and I hope your team considers.

**Comment by colinrtwhite** [comment]
Speaking honestly, this isn't likely to be implemented. Currently Coil doesn't implement any decoders itself and wraps existing decoders in Android or 3rd party libraries to decode images. Also animated SVG is a **very complex** specification and neither myself or my employer use it so there isn't a strong reason to spend development resources building a decoder from the ground up.

Ultimately https://github.com/BigBadaboom/androidsvg/issues/87 is the root issue to watch. Leaving the issue open in Coil wouldn't have any extra info and closing the issue helps keep the tracker focused on issues/features for the library itself. I updated this issue to mark it as "not planned" instead of "completed".
