### ISSUE TITLE
Debug cache indicator like Picasso?

### ISSUE THREAD

**Issue by ColtonIdle** [coil-kt/coil#1456]
**Is your feature request related to a problem? Please describe.**
Debug image loading

**Describe the solution you'd like**
Can we get debug cache loading on AsyncImage or something like picasso? https://square.github.io/picasso/

**Comment by colinrtwhite** [comment]
I think this is probably best fit as an external library or a custom implementation. It should be possible to implement something like this using a custom interceptor and wrapping the returned drawable.

I've tended to avoid adding features like this to Coil since they're opinionated and aren't easy to customize locally. It's generally better to provide an extension point for custom logic (like `Interceptor`) instead of providing an implementation that might not fit for every user.
