### ISSUE TITLE
Add support for the .ico format

### ISSUE THREAD

**Issue by Mek101** [coil-kt/coil#1464]
**Is your feature request related to a problem? Please describe.**
I'm using Coil to display link previews. If the page doesn't have an [OpenGraph](https://en.wikipedia.org/wiki/Facebook_Platform#Open_Graph_protocol) image, I fallback on searching for the website [favicon](https://it.wikipedia.org/wiki/Favicon). The issue here is that many websites only have an [`.ico`](https://it.wikipedia.org/wiki/.ico) file as their favicon.

**Describe the solution you'd like**
Add support for the `.ico` format.

**Comment by colinrtwhite** [comment]
Thanks for the request, though I think this is a good fit for a 3rd party library or a custom implementation since it's a niche format on Android. I'd recommend creating a custom `Decoder` in your code that can support this. Reusing [this code for Animated PNG](https://github.com/coil-kt/coil/issues/506#issuecomment-952526682), but using [this library](https://github.com/cmauri/image4droid) instead of the Animated PNG library should get you towards a working implementation.
