### ISSUE TITLE
Default Logging implementation of EventListener

### ISSUE THREAD

**Issue by yschimke** [coil-kt/coil#1496]
EventListener is really useful, but it would be nice to have a default implementation.

Along these lines.

```
class LoggingEventListener(
    val log: (String) -> Unit = { println(Thread.currentThread().name + ": " + it) }
): EventListener {
    override fun decodeStart(request: ImageRequest, decoder: Decoder, options: Options) {
        log("decodeStart")
    }
```

**Comment by colinrtwhite** [comment]
I'm not sure this is something we should add to Coil's API since it's opinionated (Do we log arguments as well? If so, do we call `toString()` on every argument? What about custom argument formatting?), but also easy to create a custom implementation locally. I could see users asking for a lot of different options for this API, when instead I think it's probably best to create an implementation that fits their use case locally.

**Comment by yschimke** [comment]
Makes sense.  I'd argue that OkHttp LoggingEventListener can show the benefit of a reusable implementation, but then I tend to not actually use that myself.  Happy to close.
