### ISSUE TITLE
Access disk or memory cache to retrieve cached bitmap

### ISSUE THREAD

**Issue by newmanw** [coil-kt/coil#1555]
**Describe the bug**
Trying to use memory or disk cache to retrieve cached bitmap as described here: https://github.com/coil-kt/coil/issues/100#issuecomment-939691688

**To Reproduce**
Cache bitmap:
```
val request = ImageRequest.Builder(context)
   .memoryCacheKey("key")
   .diskCacheKey("key")
   .data(bitmap)
   .build()
val result = imageLoader.executeBlocking(request) // returns successful result
```

Trying to access cached bitmap in either cache returns nul
```
val result = imageLoader.memoryCache.get(MemoryCache.Key("key") //null
val result = imageLoader.diskCache.get("key") //null
```

**Version**
io.coil-kt:coil-base:2.2.2

**Comment by colinrtwhite** [comment]
@newmanw Bitmaps passed as `data` aren't added to the memory cache since we don't want to use some of the memory cache's capacity to store a result that doesn't require fetching or decoding (as the bitmap already exists in memory). If you'd like to force adding the `bitmap` to the memory cache you can do it like this:

```kotlin
imageLoader.memoryCache?.set(MemoryCache.Key("key"), MemoryCache.Value(bitmap))
```
