### ISSUE TITLE
[Feedback] Transition API in 0.9.0

### ISSUE THREAD

**Issue by chrisbanes** [coil-kt/coil#170]
Hi all,

Had a look at the new Transition API earlier today, and added a draft PR here: https://github.com/chrisbanes/tivi/pull/526

Overall I liked the API and it achieves what I needed it to :smile:. Some small API feedback:

* Is the `Event` class really an event? Looking at the items in it, maybe `LoadResult` is a better name?
* Similarly the naming of `Transition.Adapter` isn't obvious to me. Maybe just `TransitionTarget` which extends `Target`?
* The naming of `Event.CACHED` could be clearer imo. The term `cached` is a very overloaded term, especially for image loading libraries. Maybe be more specific and call it `CACHED_MEMORY`?

Hope that helps!

**Comment by colinrtwhite** [comment]
Thanks for the quick feedback!

- Great suggestion. What do you think about just `Transition.Result`? I'm wary to add `Load` to the beginning so users don't think there's also a `GetResult`.
- Yep, `Adapter` isn't the best name either. I like `TransitionTarget`, however I want to avoid it extending `Target` since `Transition`s ideally shouldn't have knowledge of `TransitionTarget.onSuccess` or `TransitionTarget.onError` (only `TransitionTarget.drawable`).
- :+1: Makes sense. I'll change to `CACHED_MEMORY` to be more explicit.

Going to leave this thread open so others can add feedback if they'd like.

**Comment by chrisbanes** [comment]
1. `Transition.Result` sounds good to me.
2. Yep, makes sense.

**Comment by chrisbanes** [comment]
Following on from your comment on my PR: https://github.com/chrisbanes/tivi/pull/526/files/396f93fda00dbf543236647900df4f774c6d0a64#r346047675

I wonder if this can be simplified. What does the factory actually give us? Personally I think we could get rid of the `Factory` and just make each `Transformation` handle the different states and `Transition.Result`.

**Comment by colinrtwhite** [comment]
Yep, was going back and forth on adding the factory as well. Here was my thought process:

- Without the factory, each `Transition` instance will have to be stateless since it'll be called many times if registered as part of `ImageLoaderBuilder.transition`. We already kind of require this for `Transformation`s since they can be reused across many requests, however reusing the same `Transition` instance is less common.

- The factory also allows you to use different transitions for different image request results (e.g. a different transition for success and error). Not sure how useful this is in practice.

- The factory allows us to avoid calling a suspend function if we're not going to transition, which is a minor perf benefit. Maybe over-optimizing here, but wanted to avoid the extra overhead since we're not likely to transition for `Transition.Result.CACHED_MEMORY`.

I think you're probably right that we should remove the `Factory` since that makes the API simpler and follows the same design as `Transformation`. In that case I'd probably want to remove support for transitioning if the drawable is loaded from the memory cache as well (not sure how important that is).

**Comment by chrisbanes** [comment]
Hmmm, I'm not against the `Factory`, it just makes the decision tree a bit complex and spreads it across different classes. Looking at the code again, I think the current setup is good. The Factory potentially allows dependency injection, etc, which is good futureproofing too.

Maybe the `Transformation` should follow suit?

**Comment by colinrtwhite** [comment]
I think I'd want to avoid adding a factory to the `Transformation` API since It adds extra complexity to that API (Glide doesn't have one either). Overall, I'm leaning to removing the factory since I'd guess most people won't need to hold mutable state in a `Transition`. If someone needs a factory, since `Transition` only has one method, they could do something like this:

```kotlin
class CustomTransition : Transition {
    suspend fun transition(...) = OneShotTransition(...).transition()

    class OneShotTransition(...) : Transition {
        suspend fun transition(...) = TODO()
    }
}
```

I think one of the main sources of confusion at the moment is that `drawable` is nullable in `Transition.transition`. I think there needs to be better separation between the success case (where `drawable` is always not null and `onSuccess` should be called) and the error case (where `drawable` could be null and `onError` should be called).

I'd also like to remove the `setDrawable` from the transition adapter. At the moment it's kind of a weird extra callback that bypasses calling `onSuccess` or `onError`. I'm thinking `Transition.Adapter` should wrap the target (instead of having the target implement it) and handle delegating `setDrawable` to either `onSuccess` or `onError`.

Let me know what you think! Also going to spend some time playing with a few designs this weekend and report back.

**Comment by colinrtwhite** [comment]
Made some changes to the `Transitions` API [here](https://github.com/coil-kt/coil/pull/216). Shipping it as part of 0.9.0 today since there are some important fixes in master, but it's definitely still open for feedback/change!

**Comment by colinrtwhite** [comment]
Thanks again for the feedback! Closing this out.
