### ISSUE TITLE
Add support for transformations in coil-gif

### ISSUE THREAD

**Issue by damiancioo** [coil-kt/coil#176]
**Is your feature request related to a problem? Please describe.**
Right now I want to use coil's coil gif extension together with transformations, it seems that Gif extension is ignoring them

I did:
```
Coil.setDefaultImageLoader(ImageLoader(this) {
            componentRegistry {
                add(GifDecoder())
            }
        })
```
and load image with:
```
imageView.load(R.drawable.some_gif_image) {
                placeholder(R.drawable.placeholder)
                transformations(CircleCropTransformation())
                repeatCount(0)
            }
```

**Describe the solution you'd like**
Gid extension should apply transformations

**Comment by colinrtwhite** [comment]
Yep, I'd like to add support for this as well, however it'll need to account for [ImageDecoder](https://developer.android.com/reference/android/graphics/ImageDecoder) and more specifically [PostProcessor](https://developer.android.com/reference/android/graphics/PostProcessor).

`PostProcessor` has some key differences from `Transformation`s:
- It passes a `Canvas` instead of a `Bitmap`.
- The canvas behaves as if the decoded image data already exists on the canvas.

Unfortunately, I won't be able to work on this for a while, but PRs welcome.

**Comment by sagar-viradiya** [comment]
@colinrtwhite I have made suggested changes and this seems to be working fine. PR coming soon!

**Comment by prithivraj** [comment]
Hi Instacart!
This issue blocks us from switching to Coil.
Is there a planned release date for the next version?

**Comment by colinrtwhite** [comment]
@prithivraj Yep! The next release should be out either tomorrow or early next week - just need to fix one bug on master.

**Comment by colinrtwhite** [comment]
The release is delayed slightly, unfortunately as I haven't been able to solve the issue on master yet. In the meantime you can use the [snapshot builds](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots) if you need the latest changes now.

**Comment by prithivraj** [comment]
Thanks for the update Colin, I've checked with the snapshot version, everything looks good and working!
