### ISSUE TITLE
Could DecodeUtils.isSvg() be moved to coil-base?

### ISSUE THREAD

**Issue by saket** [coil-kt/coil#1811]
For adding [support for SVGs](https://github.com/saket/telephoto/issues/31) to telephoto, I need to inspect bitmaps sources if they contain an SVG. I noticed that `coil-svg` ships with a public function named [DecodeUtils.isSvg()](https://github.com/coil-kt/coil/blob/3e24b8298479dee904aff790ac8dcf7f61218f3a/coil-svg/src/main/java/coil/decode/DecodeUtils.kt#L18) that is perfect for my usecase, but it's located in `:coil-svg`. Will it be reasonable to move it to `:coil-base` so that consumers can inspect images without bringing in additional SVG related dependencies?

For now I've copy pasted `DecodeUtils.isSvg()` and `BufferedSource.indexOf(bytes: ByteString, …)` to my project.

**Comment by colinrtwhite** [comment]
I'd prefer to keep it in `coil-svg` since it's not by any internal `coil-base` components and won't be used by most projects. If we move it then there's also an argument for moving `coil-gif`'s `DecodeUtils` extensions (and any future extensions), which increases `coil-base`'s size. I think copying the method locally into your project is the best solution.

**Comment by saket** [comment]
That's fair!
