### ISSUE TITLE
support .jxl files

### ISSUE THREAD

**Issue by RustoMCSpit** [coil-kt/coil#1903]
jpeg xl, the successor to .jpg

**Comment by colinrtwhite** [comment]
Thanks for the request. I think this is a good candidate for an external library. I think your best bet would be to implement the [`Decoder`](https://coil-kt.github.io/coil/image_pipeline/#decoders) interface and wrap the [`libjxl`](https://github.com/libjxl/libjxl) native decoder library since Android doesn't have native support. JPEG XL seems to be a bit of a niche format ([Chrome deprecated and remove support last year](https://www.phoronix.com/news/Chrome-Dropping-JPEG-XL-Reasons)) and adding first party support takes time to build and maintain.

**Comment by RustoMCSpit** [comment]
> JPEG XL seems to be a bit of a niche format

most formats are only niche cause apps dont support them, jxl is a superior version of jpg and it's sad it has such little implementation
