### ISSUE TITLE
Add ImageView extension in coil-base

### ISSUE THREAD

**Issue by yoobi** [coil-kt/coil#1933]
**Is your feature request related to a problem? Please describe.**
I am implementing coil-base for my multi-module project with hilt
```kotlin
**APP MODULE**
@Module
@InstallIn(ActivityComponent::class)
class ImageLoaderModule {
    @Provides
    fun provideCoil(@ActivityContext context: Context): ImageLoader = ImageLoader.Builder(context)
        .error(AppDrawableRes.error_image_placeholder)
        .build()
}
```
To be able to use `ImageLoader` in my `home`module I've added in its build.gradle `implementation("io.coil-kt:coil-base:2.5.0")` and then to load the image we've got to use:
```kotlin
val request = ImageRequest.Builder(context)
    .data(data)
    .target(view)
    .apply(builder)
    .build()
imageLoader.enqueue(request)
```

**Describe the solution you'd like**
It would be nice to add the extension from coil-kt but with a twist:
```kotlin
inline fun ImageView.load(
    data: Any?,
    imageLoader: ImageLoader, // <-- imageLoader is now mandatory
    builder: ImageRequest.Builder.() -> Unit = {}
): Disposable {
    val request = ImageRequest.Builder(context)
        .data(data)
        .target(this)
        .apply(builder)
        .build()
    return imageLoader.enqueue(request)
}
```
So that we can directly use `imageView.load(url, imageLoader)`

**Comment by colinrtwhite** [comment]
Thanks for the suggestion. The `coil-base` artifact is focused on only providing the essentials and avoids adding extension functions to non-Coil classes. This is because `coil-base` is sometimes exposed as an `api` dependency by other libraries and any `coil-base` extension functions would be visible to their users. If you'd like to use this extension, I'd recommend copying it locally into your project.
