### ISSUE TITLE
[Coil 3] Lazy allocated BufferedSource for ImageSource

### ISSUE THREAD

**Issue by VDostoyevskiy** [coil-kt/coil#1970]
Now that we prefer ImageDecoderDecoder for API above 28
https://github.com/coil-kt/coil/pull/1969
ImageDecoder prefer a (File, Uri) not inputstream, we have no reason to preallocate a BufferedSource(this opens a native file descriptor), save this overhead since ImageDecoder will not use that fd
See https://github.com/VDostoyevskiy/coil/blob/068e566ce04e9e1d77e08b4c80c386870d876860/coil-core/src/androidMain/kotlin/coil3/fetch/AssetUriFetcher.kt#L25
https://github.com/VDostoyevskiy/coil/blob/068e566ce04e9e1d77e08b4c80c386870d876860/coil-core/src/androidMain/kotlin/coil3/fetch/ContentUriFetcher.kt#L33

**Comment by colinrtwhite** [comment]
I think we could accomplish this with an `ImageSource` overload like this:

```kotlin
fun ImageSource(
    source: () -> BufferedSource,
    fileSystem: FileSystem,
    metadata: Metadata? = null,
): ImageSource
```

Do you know how much the native file descriptor costs, though? The main downside to this change is an invalid content/asset URI will now fail at the decode stage instead of inside the fetcher where it makes more sense. Additionally, asset/content URI `ImageSource`s won't always be consumed by `ImageDecoder` as they can be consumed by custom fetchers or `SvgDecoder` or `VideoFrameDecoder` for instance.

Also I'd want to avoid importing `AssetFileSystem` as part of `coil-core`'s dependencies as I'd like to keep Coil's dependencies to a minimum. Users can set the `FileSystem` manually using `ImageRequest.Builder.fileSystem` if they'd prefer

**Comment by VDostoyevskiy** [comment]
Aha, make sense

> I think we could accomplish this with an `ImageSource` overload like this:
> 
> ```kotlin
> fun ImageSource(
>     source: () -> BufferedSource,
>     fileSystem: FileSystem,
>     metadata: Metadata? = null,
> ): ImageSource
> ```
> 
> Do you know how much the native file descriptor costs, though? 

Not many

**Comment by VDostoyevskiy** [comment]
@colinrtwhite 
I was wrong to some extent, opening a file descriptor maybe somewhat cheap(with normal JVM File, 0.2ms), but under Android's SAF, using ContentResolver, somewhat expensive though(about 6ms for SCHEME_FILE, 10 ~ 30 ms for SAF managed file), we should avoid allocating new file descriptor in these cases
