### ISSUE TITLE
coil-base: ImageView extensions unavailable without core

### ISSUE THREAD

**Issue by bmc08gt** [coil-kt/coil#207]
It seems that the ImageView extensions aren't available without bringing in the whole coil implementation. Is that correct? From what I can see from the documentation it is recommending to only bring in coil-base for dependency injection.

**Comment by colinrtwhite** [comment]
Yep, the `ImageView` extensions are intentionally part of the `coil` artifact since they rely on the default `ImageLoader`. If you're injecting your `ImageLoader` instances, the way to load images is pretty similar:

```kotlin
imageLoader.load(context, data) {
    target(imageView)
}
```

 I'm planning to rewrite that part of the docs to make it more clear that most people will prefer to use `coil` and `coil-base` is mainly for advanced users and libraries that rely on Coil.
