### ISSUE TITLE
Coil Circle transformation from master

### ISSUE THREAD

**Issue by mario** [coil-kt/coil#208]
**Describe the bug**
Something seems off. See screenshot - there's dark gray at the outer edge of a circle where it shouldn't be. All works well with 0.8.

<img width="61" alt="Screenshot 2019-12-22 at 02 40 10" src="https://user-images.githubusercontent.com/5810/71315756-d52c4800-2464-11ea-8fad-4ac855eeb109.png">

**Comment by colinrtwhite** [comment]
Good catch! Thanks for the report. This was caused by unintended integer division in https://github.com/coil-kt/coil/pull/185. https://github.com/coil-kt/coil/pull/210 fixes the issue and adds a regression test. Can you close this issue once you've verified it's fixed in the latest snapshot for your app?

**Comment by mario** [comment]
Sorry for the not-so-well-written bug, I would have followed-up eventually. Thanks for the fix, I'll test it later today!

**Comment by mario** [comment]
Seems to work nicely, thank you very much! All the best for holidays!
