### ISSUE TITLE
Flicker when changing `ByteArray` data

### ISSUE THREAD

**Issue by sproctor** [coil-kt/coil#2138]
**Describe the bug**
`AsyncImage` flickers when loading a `ByteArray` and the value changes.

**To Reproduce**
I can attempt to write one if it's not obvious why this is happening. I don't have the time for it today though.
```kotlin
val data = remember { mutableStateOf<ByteArray?>(null) }
AsyncImage(
    model = data.value,
    contentDescription = null,
)
LaunchedEffect(Unit) {
    while(true) {
        data.value = loadImage()
        delay(REFRESH_DELAY)
    }
}
```

**Logs/Screenshots**
Logs contain nothing interesting:
🧠 Successful (MEMORY) - [B@423f7c82
🧠 Successful (MEMORY) - [B@3eb4e930
🧠 Successful (MEMORY) - [B@32ae11b9
🧠 Successful (MEMORY) - [B@35cf78b5
and so on for each image

**Version**
3.0.0-alpha04 on Android and desktop

**Comment by colinrtwhite** [comment]
This is expected behaviour. When the byte array changes Coil will decode the image on a background thread by default. When Coil starts a new request it sets the image to the provided placeholder, which is empty in your example.

If you want to force the request to run synchronously you can set `ImageRequest.Builder.dispatcher(Dispatchers.Main.immediate)` though that will likely drop frames. Alternatively you can pass the currently painter as a placeholder to the `AsyncImage` to have it keep the existing image until the new one is set. You can get a reference to the displayed painter using `AsyncImage(onSuccess)`.

**Comment by sproctor** [comment]
That last option is exactly what I was looking for. Thanks for you help!
