### ISSUE TITLE
[Coil 3] Image never loads when using `Modifier#matchParentSize()`

### ISSUE THREAD

**Issue by jan-tennert** [coil-kt/coil#2186]
**Describe the bug**
After debugging for hours why my image isn't loading, I found the problem. Using the `matchParentSize()` modifier on the `AsynImage` composable causes the image to never load. 
Tried it on Android and the JVM target, both have the same problem. 

**To Reproduce**
Small JVM snippet:
```kotlin
application {
    Window(::exitApplication) {
        Box {
            AsyncImage(
                model = "any image url",
                contentDescription = null,
                modifier = Modifier.matchParentSize(), //if you comment out this line, everything works
                onState = ::println
            )
        }
    }
}
```

**Logs/Screenshots**
If this modifier is there, only the `Loading` state gets printed. 

**Version**
3.0.0-alpha06

**Comment by maanuanubhav999** [comment]
Hey @colinrtwhite I would love to give this a shot, where can I start from, any documentation I should refer to ?

**Comment by colinrtwhite** [comment]
@maanuanubhav999 I would take a look at `ConstraintsSizeResolver`. It sounds possible that it's getting stuck resolving the constraints.

**Comment by drea52693** [comment]
Hey @colinrtwhite, if the Box size isn't specified then it will make the size match the content, but in this case the content is matchParentSize(). Specifying the Box size fixes this issue. So this should be the expected behavior, no?

**Comment by colinrtwhite** [comment]
@drea52693 Agreed this is expected behaviour. I tested out the example locally and the parent composable (the box) passed `Constraints(0, 0, 0, 0)` to the `AsyncImage` meaning it never receives valid constraints to load the image.

You can either specify the `AsyncImage` should load the image at its original size using `ImageRequest.Builder.size(Size.ORIGINAL)` or set a size on the outer `Box`.
