### ISSUE TITLE
SubcomposeAsyncImage doesn't save network images properly 

### ISSUE THREAD

**Issue by Osanosa** [coil-kt/coil#2215]
SubcomposeAsyncImage after loading and saving network images may randomly wipe them. Using regular AsyncImage doesn't have same issues.

[CoilReport.zip](https://github.com/coil-kt/coil/files/15079533/CoilReport.zip)

You can check in these two apks — older one uses SubcomposeAsyncImage and has issues, while newer one reverted to regular AsyncImage and has no cache issues.

**Comment by colinrtwhite** [comment]
Hi, I can't debug the issue using APK files. Do you have a code snippit or the source project that reproduces the issue? I'd be surprised that `SubcomposeAsyncImage` behaves differently than `AsyncImage` for disk caching images since that uses the same code path.

**Comment by Osanosa** [comment]
I mean yes, that's basically the only difference,

**Comment by Osanosa** [comment]
Actually nevermind, I'll do more testing and will get back to you in a
week or so. Is there anything specific I could try like getting logs or
else?

**Comment by colinrtwhite** [comment]
@Osanosa Without a code sample that reproduces the issue it's tough to say what could be the issue. The issue could be related to a specific URL or something else in your local build.

**Comment by Osanosa** [comment]
No, literally the only difference is a usage of regular vs subcompose — same url, same everything, nothing special

**Comment by colinrtwhite** [comment]
@Osanosa I tried to reproduce this issue in the Coil sample app by only [changing](https://github.com/coil-kt/coil/blob/main/samples/compose/src/commonMain/kotlin/sample/compose/App.common.kt#L229) it to use `SubcomposeAsyncImage` instead of `AsyncImage`. The images are written and read from the disk cache as expected. I can't debug the issue without a way to reproduce it. Feel free to open a new ticket with a code snippet that reproduces the issue.

**Comment by Osanosa** [comment]
Thank you, I'm currently out of town so I'll get back to you when possible
