### ISSUE TITLE
[coil-video] Getting frame fails for certain mp4 videos

### ISSUE THREAD

**Issue by Yentis** [coil-kt/coil#2337]
**Describe the bug**
When attempting to get a video frame for specific mp4 files (in this case a screen recording on my phone), the process fails and I see this message in logcat: `getFrameAtTime: videoFrame is a NULL pointer`.

In standard Android this is fixable by using [FFmpegMediaMetadataRetriever](https://github.com/wseemann/FFmpegMediaMetadataRetriever) but this option isn't present for coil-video.

**To Reproduce**
```
val videoLoader = ImageLoader.Builder(context)
    .components { add(VideoFrameDecoder.Factory()) }
    .build()

val request = ImageRequest.Builder(context)
    .data(filePath)
    .videoFramePercent(0.5)
    .build()

val result = videoLoader.execute(request)
val bitmap = result.drawable?.toBitmapOrNull()
// Bitmap is null
```

**Version**
2.6.0

**Sample video that fails to read frames**

https://github.com/coil-kt/coil/assets/158149375/0d01ea98-f91a-46df-97cd-b73715288789

**Comment by colinrtwhite** [comment]
Does this video fail to load using `MediaMetadataRetriever` directly? If so there's not much we can do unfortunately as the issue is in the underlying decoder. I'd prefer to avoid supporting custom video decoders like `FFmpegMediaMetadataRetriever` as it adds maintenance burden. `FFmpegMediaMetadataRetriever` itself also imports large native libraries. If you'd like to use it you can add a custom `Fetcher`/`Decoder` that implements support.

**Comment by Yentis** [comment]
Yes, it fails with `MediaMetadataRetriever` as well

**Comment by colinrtwhite** [comment]
Ah unfortunately there's not much we can do to fix this in Coil then. You could report the issue to AOSP or modify the existing [VideoFrameDecoder](https://github.com/coil-kt/coil/blob/main/coil-video/src/main/java/coil3/video/VideoFrameDecoder.kt) to use `FFmpegMediaMetadataRetriever` and add it to your `ComponentRegistry`.
