### ISSUE TITLE
Request support for DrawableResource for compose multiplatform

### ISSUE THREAD

**Issue by Junzz0** [coil-kt/coil#2345]
**Is your feature request related to a problem? Please describe.**
Loading a DrawableResource with coil will cause a crash.

```
    val imageLoader = rememberAsyncImagePainter(
        model = painterResource(Icons.ABC),
    )

    Image(
        painter = imageLoader,
        contentDescription = contentDescription,
    )
```

Icons.ABC is DrawableResource

https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

**Describe the solution you'd like**
Request support for DrawableResource for compose multiplatform

**Comment by colinrtwhite** [comment]
Yep, this is planned to be next up now that `alpha07` is out. There's already a ticket tracking support [here](https://github.com/coil-kt/coil/issues/2077).

Just to note `rememberAsyncImagePainter(painterResource(Icons.ABC))` will always crash since you can't pass a `Painter` to `rememberAsyncImagePainter`. `Painter`s should be passed directly to `Image`. This should be supported, though:

```kotlin
AsyncImage(
  model = Res.getUri("files/my_photo.jpg"),
  contentDescription = null,
)
```

**Comment by mrnorbertf** [comment]
@colinrtwhite  any update?
