### ISSUE TITLE
Coil3 alpha-08 not compatible with ktor 3.0-beta02

### ISSUE THREAD

**Issue by revonateB0T** [coil-kt/coil#2377]
For more details, see https://github.com/coil-kt/coil/issues/1944#issuecomment-2230012165

**Comment by colinrtwhite** [comment]
Unfortunately it's a bit complicated since Ktor didn't change its package name so it's not possible to import both Ktor 2 and Ktor 3 at the same time. I'm guessing other libraries that integrate with Ktor will run into similar binary incompatibility issues. We have a couple options:

1. Update `coil-network-ktor` to depend on the Ktor 3.0 betas. This isn't ideal since it forces everyone who uses Coil to also update their Ktor dependency to a beta version. We also can't release Coil 3 without a stable Ktor 3 release then. I don't think we should do this.
2. Publish a separate `coil-network-ktor3` artifact (and probably rename `coil-network-ktor` to `coil-network-ktor2`?). Ideally I'd like to avoid this since it adds more maintenance burden to Coil and we'll probably stop supporting Ktor 2 when Ktor 3 becomes stable.
3. Wait until Ktor 3 is stable to update. This probably isn't a good idea since we don't want to block downstream dependencies from using Ktor 3.

I think we'll probably have to do #2. Users will still run into issues if other libraries import Ktor 2.x, but at least we can unblock users depending on Coil.

**Comment by tylerwilson** [comment]
I would vote #2. It is possible Ktor 2.x may be alive for longer than we like, but we would also like to have a Ktor 3.x compatible version of Coil as soon as is reasonable. :-)
