### ISSUE TITLE
Investigate SieveCache as coil memory cache for better performance

### ISSUE THREAD

**Issue by revonateB0T** [coil-kt/coil#2385]
For reference,

https://github.com/androidx/androidx/blob/85d3f8158b2f9b26cc014a5c9c8793b188544d1f/collection/collection/src/commonMain/kotlin/androidx/collection/SieveCache.kt#L40

https://android-review.googlesource.com/c/platform/frameworks/support/+/3182934

https://android-review.googlesource.com/c/platform/frameworks/support/+/3180757

**Comment by revonateB0T** [comment]
Conclusions: SieveCache has following advantages.
1. better hit ratio?(It should depends on application(not coil)'s workload)
2. Fully kotlin implementation, less platform behaviour differences.
3. Allocation free, lock free.

**Comment by colinrtwhite** [comment]
@revonateB0T Interesting! Do you know how `SieveCache` achieves a better hit rate vs. an LRU cache? It sounds like it still keeps track of the most recently accessed entries and evicts the eldest when it needs space.

In terms of perf my suspicion is `LruCache` might come out ahead on the JVM since it's backed by a `LinkedHashMap`, which is heavily optimized by JIT. Coil's `LruCache` implementation is also already lock free (but not allocation free).

Unfortunately I think the largest bottleneck to adopting this is `androidx.collection`'s lack of support for the JS and wasmJS targets. Even if they do eventually add these targets there's no guarantee that they'll quickly add support if new targets get added by Kotlin, which would potentially block Coil from supporting new targets.

**Comment by revonateB0T** [comment]
> Do you know how `SieveCache` achieves a better hit rate vs. an LRU cache?

Nope.

> In terms of perf my suspicion is `LruCache` might come out ahead on the JVM since it's backed by a `LinkedHashMap`, which is heavily optimized by JIT. Coil's `LruCache` implementation is also already lock free (but not allocation free).

Yeah, you are right, `LinkedHashMap` is already aot-ed on Android, but it implemented a `interface` and call side needs invoke-virtual so methods will not be heavily inlined I think.

> Unfortunately I think the largest bottleneck to adopting this is `androidx.collection`'s lack of support for the JS and wasmJS targets. Even if they do eventually add these targets there's no guarantee that they'll quickly add support if new targets get added by Kotlin, which would potentially block Coil from supporting new targets.

It's not a problem. `SieveCache` is fully kotlin implemented, so we can fetch it to our codebase and compile to JS and wasmJS, no need to add platform dependent code, just like what we do for `LruCache`.

**Comment by colinrtwhite** [comment]
> It's not a problem. SieveCache is fully kotlin implemented, so we can fetch it to our codebase and compile to JS and wasmJS, no need to add platform dependent code, just like what we do for LruCache.

SieveCache is a pretty large, complex class whereas LruCache is ~100 lines. I'm not sure it's worth maintaining a SieveCache fork unless it has a clear performance benefit.

**Comment by revonateB0T** [comment]
> SieveCache is a pretty large, complex class whereas LruCache is ~100 lines. 

It's not that, most method is useless if we decided to trim it ourselves. But I'm not suggesting to do that, I'd like just keep sync with upstream.

**Comment by colinrtwhite** [comment]
Thanks for the suggestion, but if we're not sure `SieveCache` will improve hit rate I don't think it's worth the extra effort to keep a local implementation in sync with upstream.
