### ISSUE TITLE
Coil 3: Differing APIs make writing multiplatform code fiddly

### ISSUE THREAD

**Issue by iamcalledrob** [coil-kt/coil#2429]
**Is your feature request related to a problem? Please describe.**
My specific use-case: I have a multi-platform codebase using coil 3 (android, JVM)
1. I have a workflow that requires `allowHardware(false)` to be specified for Android
2. The method `ImageRequest.Builder.allowHardware` is only available in Coil's androidMain sourceSet
3. I need to implement this in a common sourceSet that's shared between Android and JVM
4. This is not possible because `allowHardware` is undefined on JVM

**Describe the solution you'd like**
Ensure the APIs are the same on all supported platforms, and either noop or throw a NotImplementedException if the method isn't supported.

Currently, I have to work around like this, which isn't ideal:
```kotlin
// commonMain/.../Coil+HardwareBitmaps.kt
expect fun ImageRequest.Builder.androidAllowHardware(b: Boolean): ImageRequest.Builder

// androidMain/.../Coil+HardwareBitmaps.android.kt
actual fun ImageRequest.Builder.androidAllowHardware(b: Boolean): ImageRequest.Builder = allowHardware(b)

// jvmMain/.../Coil+HardwareBitmaps.jvm.kt
actual fun ImageRequest.Builder.androidAllowHardware(b: Boolean): ImageRequest.Builder = this
```

**Additional context**
Thanks for making coil, it's brilliant :)

**Comment by colinrtwhite** [comment]
It's a bit more cumbersome, but I think this makes sense as is. Generally multiplatform APIs should only be available on platforms that they're supported on, as it signals which APIs are platform-specific and which are available on all platforms.

Also making `allowHardware` a common API would create a consistency issue, as some similar APIs couldn't be in `commonMain`. For instance, we can't make `bitmapConfig` a common API as `Bitmap.Config` is only available on Android.

**Comment by iamcalledrob** [comment]
I understand your perspective - thanks for considering, I appreciate it!


Some more thoughts for a rainy day:

> Generally multiplatform APIs should only be available on platforms that they're supported on

I agree with this when working in a language that supports #ifdefs or an equivalent. Unfortunately Kotlin doesn't, which is what makes the experience awkward.

My personal preference (shaped by the Golang world, which doesn't have #ifdefs either) would be that the package provides a common interface for methods that are callable from a common sourceSet. Basically, as little as possible is put into platform-specific places, because calling that code is awkward. i.e.:
- Common code doesn't include methods that take/return platform types like `android.graphics.Bitmap` -- because this can *only* be called from a platform sourceSet
- Common code *does* include methods like `allowHardware()` which may be needed in common code and are callable from a common sourceSet

My specific situation, if you're curious, is that I have common desktop/android UI components which get captured later in android-specific code using `Picture.beginRecording()`. This fails if hardware bitmaps are used.

**Comment by colinrtwhite** [comment]
Thanks for the suggestion, but I think it's best not to mix platform-specific APIs into common code. For example, `SvgDecoder` on Android has an [`ImageRequest.Builder.css` method](https://github.com/coil-kt/coil/blob/main/coil-svg/src/androidMain/kotlin/coil3/svg/imageRequests.android.kt#L12). This is only supported on Android due to platform support. We could promote the method to `commonMain` since it only takes a string, but it will be unexpected when `css` is ignored silently on other platforms.

In your example `allowHardware` is an Android-specific `ImageRequest` config value. I could see someone have the same need to set `bitmapConfig` from common code, however it's not possible to upgrade `bitmapConfig` to `commonMain`. Essentially I don't think we should treat these two methods differently because one uses a platform type and one could be in `commonMain`. We should treat them consistently in the API surface. If the APIs aren't supported on a platform we should make that clear vs. silently ignoring the value.
