### ISSUE TITLE
Coli3: Async image not loading - neither onSuccess or onError is being called

### ISSUE THREAD

**Issue by slickorange** [coil-kt/coil#2462]
**Describe the bug**
I am trying to display an AsyncImage in a Compose multiplatform project. 

On Android nothing happens. I don't get an error message but neither `onSuccess` or `onError` is called. (`onLoading` is called) 
When I go back to the previous screen I can see the loading request being cancelled in the logs.

Any ideas?

Also I am finding it hard to gather exactly which dependencies I need to rely on to properly use Coil with compose multiplatform. There are various different articles on the web but the official Coil documentation does not seem very clear on this (unless I am missing something)

On Web (js) I get an error

**To Reproduce**

I am calling AsyncImage like this
```
            coil3.compose.AsyncImage(model = "https://fastly.picsum.photos/id/280/200/200.jpg?hmac=jjE26x23XLyRTL5st1-nb_BAHldv1V3JoFRn4g_nN04", contentDescription = "Art",
                onLoading = {
                    println("Loading image")
                            },
                onSuccess = {
                    println("Success")
                            },
                onError = {
                    println("Error")
            } )
```

In my `App.kt` App() function I do:
```
    setSingletonImageLoaderFactory { context ->
        getAsyncImageLoader(context)
    }
```

And also in `App.kt` I have:
```
fun getAsyncImageLoader(context: PlatformContext)=
    ImageLoader.Builder(context).build()
```

**Logs/Screenshots**

No specific errors on Android.

On web (js) I get:

```
JsClientEngine.kt:49 Uncaught (in promise) AbortError: BodyStreamBuffer was aborted
    at InvokeOnCancelling.eval [as handler_1] (JsClientEngine.kt:49:24)
    at protoOf.invoke_py2q9a_k$ (JobSupport.kt:1569:68)
    at notifyCancelling (JobSupport.kt:365:26)
    at makeCancelling (Standard.kt:158:32600)
    at protoOf.cancelImpl_465b6c_k$ (JobSupport.kt:702:26)
    at protoOf.cancelInternal_fraw7c_k$ (JobSupport.kt:663:9)
    at protoOf.cancel_hkmm2i_k$ (JobSupport.kt:648:9)
    at cancel_2 (CoroutineScope.kt:284:9)
    at cancel_1 (CoroutineScope.kt:292:85)
    at protoOf.doResume_5yljmg_k$ (DefaultTransform.kt:98:34)
```

**Version**
3.0.0-alpha08

**Comment by colinrtwhite** [comment]
Sorry - agreed the docs are a bit unclear at the moment. I need to do a full pass to update the logs to 3.x once it's complete. For the moment I'd use [this page](https://coil-kt.github.io/coil/upgrading_to_coil3/) as a reference. For loading network images you need [these dependencies](https://coil-kt.github.io/coil/upgrading_to_coil3/#network-images) along with `coil-compose`.

For the cancellation issue it's not possible to say what the issue is without a sample that reproduces the bug locally. From the logs it sounds like it could be a Ktor issue? The request will be automatically cancelled when leaving the composition/screen, but it's not clear why it's taking a long time to load the image internally.
