### ISSUE TITLE
Disparity between coil2 and coil3's equality delegate

### ISSUE THREAD

**Issue by saket** [coil-kt/coil#2640]
While migrating telephoto to coil3, I noticed that some of my tests were running into infinite loops of image requests because the new equality delegate does not account for non-`ImageRequest` models.

| Coil 2.x | Coil 3.x |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/df1721e3-976a-427b-a82f-2fea92f742af) | ![image](https://github.com/user-attachments/assets/88a70163-d225-42b8-91e7-2617fcc25a32) |

Was this an intention choice? 

Here's how I'm using `AsyncImageModelEqualityDelegate`: https://github.com/saket/telephoto/blob/5d156f836441b2deb684427162ac22d5d00f29a6/zoomable-image/coil3/src/main/kotlin/me/saket/telephoto/zoomable/coil3/ZoomableAsyncImage.kt#L112

It's also interesting that `AsyncImage()` does not seem to run into this problem. Are you relying on something else for diffing non-`ImageRequest` models?

**Comment by colinrtwhite** [comment]
Good catch! This is definitely a bug. Added a fix [here](https://github.com/coil-kt/coil/pull/2642) that we can ship in a `3.0.1` release.

There are a bunch of tests around when `AsyncImage`/`rememberAsyncImagePainter` recompose [here](https://github.com/coil-kt/coil/blob/main/coil-compose-core/src/androidInstrumentedTest/kotlin/coil3/compose/AsyncImagePainterTest.kt#L823). I think it might be recomposing infinitely for you because Coil has overloads [here](https://github.com/coil-kt/coil/blob/main/coil-compose-core/src/commonMain/kotlin/coil3/compose/AsyncImagePainter.kt#L81) that "wrap" passing the `AsyncImageState` to the "real" stable, restartable implementation [here](https://github.com/coil-kt/coil/blob/main/coil-compose-core/src/commonMain/kotlin/coil3/compose/AsyncImagePainter.kt#L134).

**Comment by saket** [comment]
That was fast, thank you!
