### ISSUE TITLE
Coil 3.0.1: scaleType fitXY, doesnt work when crossfade is enabled

### ISSUE THREAD

**Issue by Andr3Carvalh0** [coil-kt/coil#2661]
**Describe the bug**
When loading an image to a ImageView with the `scaleType` as `fitXY`, coil fails to resize the image correctly if `crossfade` is enabled. No error is shown in the stacktrace.

<img src="https://github.com/user-attachments/assets/bea39d5b-5b62-432a-aaae-2e4fca6a3cb1" width="200">

**To Reproduce**
Simply have an ImageView with `scaleType` as `fitXY`, and try to load an image to it using coil (with crossfade enabled). You can find a sample project here: https://github.com/Andr3Carvalh0/Coil3

**Version**
Coil 3.0.1

**Comment by IndusAryan** [comment]
facing same here especially in a shapeable image view

**Comment by colinrtwhite** [comment]
Thanks for the repro project. I think this is working as intended and the behavior has not changed from 2.7.0. `FIT_XY` is a special scale type in that it doesn't preserve the image's aspect ratio. `CrossfadeDrawable` only supports scaling images and preserving their aspect ratio, which is why it doesn't fill the height. `CrossfadeDrawable` doesn't support custom `MATRIX` scaling either. Adding support for these scale types would add a decent amount of complexity.

If you'd like support for this you can set a custom `transitionFactory` on your `ImageRequest` and modify `CrossfadeDrawable`.

**Comment by colinrtwhite** [comment]
@Andr3Carvalh0 Ah sorry you're right - there appears to be a bug with the code that converts `ImageView.ScaleType` into `Scale.FILL`. In 2.7.0 it's working correctly and using `Scale.FILL`; in 3.0.0 it's not working correctly and is using `Scale.FIT` (the default). I'll put up a fix soon. In both versions the image aspect ratio is still preserved.

**Comment by Andr3Carvalh0** [comment]
@colinrtwhite Thank you for the help! 😄
