### ISSUE TITLE
DiskCache should delete files that no longer exist during initialization.

### ISSUE THREAD

**Issue by panpf** [coil-kt/coil#2667]
**Describe the bug**
I used the DiskLruCache in my project, and I found a problem.

After calling evictAll(), all entities in memory and files on disk have indeed been deleted, and size() also returns 0. However, when the App is killed from the recent tasks and reopened (the test ensured that no download behavior was triggered after restart), the result returned by DiskLruCache's size() is greater than 0.

I pulled the journal files before and after the restart and compared them and found that after the App was restarted, there were still CLEAN records of all or part of the files.

I repeatedly studied the source code of DiskLruCache and found that flush() was not executed in evictAll() or flush() was triggered only in the middle of the loop execution of removeEntry(). The REMOVE record in the journal was incomplete when the app was restarted. Then, when DiskLruCache was initialized after the App was restarted, the Entry was added to lruEntries without checking whether the Entry file existed, which eventually caused this problem.

**To Reproduce**
Any API LEVEL can be reproduced on the Android emulator

**Comment by panpf** [comment]
My modification suggestions:
```kotlin
fun initialize() = synchronized(lock) {
        if (initialized) return

        // If a temporary file exists, delete it.
        fileSystem.delete(journalFileTmp)

        // If a backup file exists, use it instead.
        if (fileSystem.exists(journalFileBackup)) {
            // If journal file also exists just delete backup file.
            if (fileSystem.exists(journalFile)) {
                fileSystem.delete(journalFileBackup)
            } else {
                fileSystem.atomicMove(journalFileBackup, journalFile)
            }
        }

        // Prefer to pick up where we left off.
        if (fileSystem.exists(journalFile)) {
            try {
                readJournal()
                processJournal()
                filterFileNotExistEntry()
                initialized = true
                return
            } catch (_: IOException) {
                // The journal is corrupt.
            }

            // The cache is corrupted; attempt to delete the contents of the directory.
            // This can throw and we'll let that propagate out as it likely means there
            // is a severe filesystem problem.
            try {
                delete()
            } finally {
                closed = false
            }
        }

        writeJournal()
        initialized = true
    }

    private fun filterFileNotExistEntry() {
        for (entry in lruEntries.values.toTypedArray()) {
            if (entry.readable && entry.currentEditor == null && !entry.zombie) {
                val allExist = entry.cleanFiles.all { fileSystem.exists(it) }
                if (!allExist) {
                    removeEntry(entry)
                }
            }
        }
    }
```

**Comment by colinrtwhite** [comment]
Thanks for reporting this! I was able to reproduce this as well - though it only seems to happen inconsistently when the process is closed immediately after writing to the journal.

> flush() was not executed in evictAll() or flush() was triggered only in the middle of the loop execution of removeEntry()

Yep I think is the main source of the issue. I think we need to flush when `REMOVE` is written as well. We should probably flush 100% of the time when writing to `journalWriter` to avoid bytes being left unwritten. I opened a PR [here](https://github.com/coil-kt/coil/pull/2684/files) to implement this.

I think deleting the entry if its files are empty works, but it patches the symptom - not the root cause - which is the journal inconsistency. What do you think?

**Comment by panpf** [comment]
Yes, the root cause of the problem is the loss of REMOVE records. We should try to reduce the probability of REMOVE record loss as much as possible, but we also need to delete the entry of the lost file during initialization, because there will always be unexpected accidents.

**Comment by panpf** [comment]
I thought you didn't flush when deleting the entry in order to improve the performance during deletion, so I considered sacrificing performance to check whether the file is lost during initialization.

In fact, as long as the probability of record loss can be reduced as much as possible, there is no need to check during initialization. get() will check whether the file is lost. This problem only affects size()

**Comment by colinrtwhite** [comment]
@panpf Yep, I think `flush` was avoided in those cases for performance (I copied it from OkHttp). Overall it's pretty cheap to call `flush` so I think it's better to call it for all journal writes to prioritize the integrity of the journal.

I haven't been able to repro the issue since adding the `flush` calls, but if this reoccurs we could consider checking the files on initialization.
