### ISSUE TITLE
BlurTransformation Does not check render script maximum radius (25f)

### ISSUE THREAD

**Issue by NLLAPPS** [coil-kt/coil#290]
BlurTransformation allows changing radius and it should check for maximum possible 25f radius to prevent crash

It should (probably) also limit for sampling rates below 1f to some hard coded minimum as you can easily create out of memory crashes

**Comment by colinrtwhite** [comment]
Thanks for the report. I've added a max radius [here](https://github.com/coil-kt/coil/pull/291). I agree it's possible to choose a very small sampling rate and run out of memory, however I'm not sure there's a good minimum since `0.1`, for instance, could be fine for a small input bitmap, but too small for a large bitmap. It also depends on the device and the amount of RAM it has.
