### ISSUE TITLE
ImageView preserves the size of the PlaceHolder when loaded

### ISSUE THREAD

**Issue by rmiragaya** [coil-kt/coil#548]
**Describe the bug**

Hi!. When added a placeholder and RoundedCornersTransformation, the final image is left with that size (of the placeHolder)

My code:
`imageView1.load("https://waterfall-750x500.jpg") {
            transformations(RoundedCornersTransformation(30f))
            placeholder(R.drawable.ic_place_holder)
            scale(Scale.FILL)
        }`

` <ImageView
        android:id="@+id/imageView1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:scaleType="fitCenter"/>`

I tried with Scale.FILL, Scale.FIT and without it

**Expected behavior**
![coil_imagebug](https://user-images.githubusercontent.com/39171888/95346137-e3cbda80-0891-11eb-963d-2ffe1ed788ec.png)

first image is how it looks with the placeHolder, the second is without it and how it should looks.

**To Reproduce**
The code i just posted with any icon as a placeholder

**Version**
io.coil-kt:coil:1.0.0-rc3

Thanks a lot

**Comment by colinrtwhite** [comment]
You might be running into issues since you're using `wrap_content` for both width and height. I'm not able to reproduce this locally - can you post a small sample project that reproduce the issue?

**Comment by rmiragaya** [comment]
Hi @colinrtwhite , I created a project recreating the bug [https://github.com/rmiragaya/CoilBugExample](url)

**Comment by colinrtwhite** [comment]
Thanks for the repro project, however this is currently working as intended. This is what's happening:

- Without the placeholder, the size resolver will fall into [this case](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/size/ViewSizeResolver.kt#L109) since the view's width/height is -1 and we can't determine the view's true dimensions.
- With the placeholder, the placeholder sets the image view's size to the placeholder's dimensions. `ViewSizeResolver` then uses its width for the width of the image (height is set to ~900px due to `ConstraintLayout` constraints).

If you'd like the image to be loaded at its original size instead of the view's size you should set `size(OriginalSize)` on your request.

That said, I'm going to keep this report open to see if there's a better way we could handle this case.

**Comment by xanscale** [comment]
@colinrtwhite  same problem here
- view with fixed sizes in dp
- placeholder and remote image with differente sizes
- first run that pass through placeholder will fail size
- second run that use cache will size correctly
