### ISSUE TITLE
Migrate to kotlin-parcelize plugin as kotlin-android-extensions is deprecated

### ISSUE THREAD

**Issue by VincentJoshuaET** [coil-kt/coil#579]
I cannot build my app because this library depends on kotlin-android-extensions. I'm using Kotlin 1.4.20-RC

**Comment by colinrtwhite** [comment]
@VincentJoshuaET Is `kotlin-android-extensions` not usable from `1.4.20-RC`? What error message do you see? I don't think we can use `kotlin-parcelize` until Kotlin `1.4.20` is stable.

**Comment by VincentJoshuaET** [comment]
It is usable, but using Parcelize from kotlin-android-extensions will show a deprecation warning. Can't we have a 1.0.1-RC?

**Comment by colinrtwhite** [comment]
@VincentJoshuaET Is it possible to ignore the message? I'm not sure why your app doesn't build if it's only a warning. We try to only update to stable dependency versions.

**Comment by RavioliWonton** [comment]
> 
> 
> @VincentJoshuaET Is it possible to ignore the message? I'm not sure why your app doesn't build if it's only a warning. We try to only update to stable dependency versions.

It is because [kotlin-android-extensions-runtime](https://github.com/JetBrains/kotlin/tree/master/plugins/android-extensions/android-extensions-runtime) introduced by kotlin-android-extensions plugin and [kotlin-parcelize-runtime](https://github.com/JetBrains/kotlin/tree/master/plugins/parcelize/parcelize-runtime) introduced by kotlin-parcelize plugin share the same class name and codebase (to be exactly, kotlin-parcelize just [extracted](https://github.com/JetBrains/kotlin/commit/b7796d63d861680f2ca8de4e68c121a55aae88de#diff-45ec35a81541bb11402b3c3840af1ba7d31b7b28bf536d6d86fa5f764165744e) from kotlin-android-extension due to [this issue](https://youtrack.jetbrains.com/issue/KT-40030)), so they obviously have conflict under the same classpath, just migrate the kotlin-android-extensions plugin to kotlin-parcelize when Kotlin 1.4.20 released will fix this.
Also, the project build.gradle file contains obsolete build config like androidExtensions.isExperimental (which is [deprecated](https://youtrack.jetbrains.com/issue/KT-32096) since parcelization is not experimental function any more).

**Comment by colinrtwhite** [comment]
@VincentJoshuaET @RavioliWonton I've updated the main branch to use `1.4.20-RC`. The next Coil library version will use `1.4.20` and the `kotlin-parcelize` plugin once it releases, but in the meantime you can use the [latest snapshot](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots).

**Comment by RavioliWonton** [comment]
Kotlin [1.4.20](https://github.com/JetBrains/kotlin/releases/tag/v1.4.20) has released, and [fix](https://youtrack.jetbrains.com/issue/KT-42342) this issue by simply moving the old runtime to kotlin-android-extensions-runtime, so using 1.0.0 with Kotlin 1.4.20 will be just fine.

**Comment by rourkepoulton99** [comment]
I saw this great answer which worked for me. 
1. Go to gradle app module
2. Outside of the android block before the depencies add this :
androidExtensions {
experimental = true
features = ["parcelize"]
}
3. Make sure you have these plugins applied:
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
