### ISSUE TITLE
Add transformations for scale types (center crop, center inside, etc.)

### ISSUE THREAD

**Issue by dlew** [coil-kt/coil#617]
**Is your feature request related to a problem? Please describe.**

If you are...

1. Loading an image (but NOT into an ImageView)
2. Specifying a size for it (rather than using its natural bounds)

...Then there's no built-in way to define the way that the image should be cropped.

**Describe the solution you'd like**

Built-in transformations for the equivalents of [`ImageView.ScaleType`](https://developer.android.com/reference/android/widget/ImageView.ScaleType).

**Additional context**

There are plenty of places in our UI where we need an image but it's not being loaded directly into an ImageView:

- [Notification large icons](https://developer.android.com/guide/topics/ui/notifiers/notifications#Templates)
- [Chip icons](https://developer.android.com/reference/com/google/android/material/chip/Chip)
- [App shortcut icons](https://developer.android.com/guide/topics/ui/shortcuts)
- [ImageSpans](https://developer.android.com/reference/android/text/style/ImageSpan) (seen in [Markdown](https://spec.commonmark.org/0.29/#images))

**Comment by jobernolte** [comment]
Maybe this code I'm using in my project could be used as a starting point.

[CropTransformation.zip](https://github.com/coil-kt/coil/files/6062557/CropTransformation.zip)

**Comment by colinrtwhite** [comment]
Sorry to close this issue after letting it sit for a while, but I think this would fit best as an external library. I'm not sure these would get significant usage if they were included in the main artifact and it's possible to implement these using the existing `Transformation` API. If I had the choice today I probably wouldn't include the existing transformations (circle crop and rounded corners) that are included in the main artifact, however they're grandfathered in due to their high usage.

I've thought about having a `coil-transformations` artifact where we could add transformations like these. Though, I've shied away from creating it so far since it would distract from working on Coil's core and it would likely be a lot more code/API to maintain. Also, there are often better, faster ways to perform transformations nowadays (e.g. `ShapeableImageView` in views and `Modifier.clip(RoundedCornerShape(radius))` in Compose).
