### ISSUE TITLE
ImageView not getting `onSuccess` call if it's in `GONE` state and have one of settings `layout_width`/`layout_height` set as `match_parent`

### ISSUE THREAD

**Issue by admund** [coil-kt/coil#740]
**Describe the bug**
ImageView not getting `onSuccess` call if it's in `GONE` state and have one of settings `layout_width`/`layout_height` set as `match_parent`.

**Expected behavior**
Listener should get this call :)

**To Reproduce**
Layout:
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:id="@+id/message_image_view"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:visibility="gone"
        android:layout_centerInParent="true"/>

</RelativeLayout>
```

Load:
```
findViewById<ImageView>(R.id.message_image_view).apply {
  load("https://media.tenor.com/images/07897c06242f1329ef7c37878b6bed94/tenor.png") {
      listener(
              onStart = {
                  Log.e("ZXC", "onStart")
              },
              onSuccess = { _, _ ->
                  Log.e("ZXC", "onSuccess")
                  visibility = View.VISIBLE
              }
      )
  }
}
```

**Version**
1.2.0

**Comment by colinrtwhite** [comment]
I tried to reproduce this in the `coil-sample` project, but was unable to. Do you have a sample project I could look at? Also are you sure `onError` isn't being called instead of `onSuccess`?

**Comment by henningBunk** [comment]
Can confirm. Using `wrap_content` works. Using `match_parent` or an equivalent constraint layout does not work.

The `onSuccess` callback is never called for me. (Neither `onError`). It does not matter if you set the image view to gone before the request or inside the `onStart` callback.

Somehow the `onStart` callback is called twice for me. Dont know if related though.

**Comment by admund** [comment]
@colinrtwhite https://github.com/admund/coil_issue_740

**Comment by colinrtwhite** [comment]
Thanks for the repo project - I'll take a look into this.

**Comment by colinrtwhite** [comment]
This is due to `RelativeLayout` [not measuring its children until they're visible](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/widget/RelativeLayout.java#476). Unfortunately I don't think there's a better way for Coil to handle this as it needs measured view dimensions to know what size to load the image at. Fortunately, the request will get valid dimensions as soon as the view is set to visible and will complete the request as normal. Overall I'd say this is expected behaviour (Glide behaves the same way in this case).
