### ISSUE TITLE
Automatically choose between animatedTransformation and transformations if both are set

### ISSUE THREAD

**Issue by edenman** [coil-kt/coil#773]
**Is your feature request related to a problem? Please describe.**
I am trying to load images from user-provided URLs and I don't know ahead of time if the result will be a bitmap or an animated gif.  I want to circle-crop the result either way, but afaict this is not supported.

**Describe the solution you'd like**
If there's an `animatedTransformation` on the request builder and the result is animated, don't apply `transformations`.  If the result is _not_ animated, apply `transitions` normally.

**Comment by edenman** [comment]
I think something like [this](https://github.com/coil-kt/coil/compare/main...edenman:main) would do it, but I'm not sure about a couple things:
1) Is there a cleaner way to check for the presence of an animatedTransformation aside from copying the string and checking for the presence of the parameter manually?  We can't access `Parameters.animatedTransformation()` from coil-base
2) Not familiar with the testing infrastructure here but we'll definitely want some tests for this.

**Comment by colinrtwhite** [comment]
@edenman What do you think about adding an `ImageRequest`/`ImageLoader` option to disable [the behaviour that converts the drawable to a bitmap](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/intercept/EngineInterceptor.kt#L345) if there's a `Transformation` in the request. If it's disabled:

- If the URL turns out to be a GIF (or non-`BitmapDrawable`) the `Transformation` will be ignored and it'll output the GIF with the animated transformation.
- If the URL turns out to be an image (or any kind of `BitmapDrawable`) the `Transformation` will be used and the animated transformation will be ignored.

That way we don't need to have knowledge of animated transformations in `coil-base` also. Could maybe name the API something like `ImageRequest.allowConversionToBitmap(false)`?

**Comment by colinrtwhite** [comment]
If you're interested in implementing this, you can probably use [Romain's `premultipledAlpha` PR](https://github.com/coil-kt/coil/pull/569) as a template (since it adds to `ImageRequest`). Else, I can probably take this on sometime soon.

**Comment by edenman** [comment]
That works.  I'll whip something up.  Should `animatedTransformation()` set this new flag automatically? I think yes, but might be a bit too magical?

**Comment by edenman** [comment]
https://github.com/coil-kt/coil/pull/775

**Comment by colinrtwhite** [comment]
@edenman Hmm my gut feeling is that it shouldn't set it automatically since it's a bit magical, but I also can't think of a case where you'd want `allowConversionToBitmap` to be true if there's an animated transformation.

**Comment by edenman** [comment]
Yeah, I'm torn
