### ISSUE TITLE
Default to clearing an image rather than throwing an exception if ImageRequest data is null

### ISSUE THREAD

**Issue by Amagi82** [coil-kt/coil#814]
Allowing null in `ImageView.load()` but then throwing a NullRequestDataException (even if it's just caught and logged) seems like a very odd choice. 

I feel like there are two sensible choices: 
1. Clear the ImageView if the data is null. This is fairly standard behavior. 
2. Don't allow nulls to be passed into ImageView.load()

Not doing that means you have to either manually check every single load call for nullability, or just put up with huge amounts of stack trace data polluting your logs. And I imagine the current method is considerably less efficient than just checking for null immediately in loadAny and not creating a request if there's no point in doing so.

Thoughts?

**Comment by colinrtwhite** [comment]
The first option is effectively already what happens. You can create a custom `Logger` that ignores `NullRequestDataException` if you don't want to show them in your logs.

In terms of why it's designed this way, Coil (same with Glide) has support for a `fallback` drawable which is used if `ImageRequest.data` is null. To show the fallback drawable we need to call either `Target.onSuccess` or `Target.onError`. To be consistent, Coil treats the null data as an error and then calls `Target.onError`. This also allows consumers to decide how they want to react to null data instead of failing silently.

**Comment by colinrtwhite** [comment]
Closing this out as I don't think we can make this change.

**Comment by ninovanhooff** [comment]
Another approach is to use `fallback = ColorPainter(Color.Transparent)`
