### ISSUE TITLE
Compose Image inside ScrollableTabRow doesn't start loading without size modifier

### ISSUE THREAD

**Issue by PhilipDukhov** [coil-kt/coil#862]
Image inside composable without size modifiers starts loading and gets size of the picture at the end

But when wrapped in `ScrollableTabRow` it doesn't start downloading. Adding `Modifier.size(40.dp)`, `Modifier.width(40.dp)` or `Modifier.height(40.dp)` solves this issue
```
ScrollableTabRow(
    selectedTabIndex = 0,
) {
    Image(
        painter = rememberImagePainter("https://via.placeholder.com/300.png"),
        contentDescription = null,
    )
}
```
Expected behaviour: as `ScrollableTabRow` has it's own max height, if the image height is bigger tab height, I expect image to be resized to that height saving aspect ratio by default

Coil: 1.3.2
Compose: 1.0.1

**Comment by colinrtwhite** [comment]
Thanks for the report, however this is currently intended behaviour ([mentioned here](https://coil-kt.github.io/coil/compose/#migrating-from-accompanist)). You can set `ImageRequest.size(OriginalSize)` to have the image display without an `Image` size.

It's not possible to display an image without specifying the size due to [a compose design decision](https://issuetracker.google.com/186012457). Accompanist uses a timer internally to work-around this however, timers can be flaky which is why it was removed in `coil-compose`.

**Comment by PhilipDukhov** [comment]
@colinrtwhite Thanks for clarifying this. 

But plain `Image` without specified size works fine, just like this:
```
Image(
    painter = rememberImagePainter("https://via.placeholder.com/300.png"),
    contentDescription = null,
)
```
That's what made me think that wrapping in `ScrollableTabRow` causes a bug
