### ISSUE TITLE
Introduce an easy way to provide composable functions for all ImagePainter states (loading etc)

### ISSUE THREAD

**Issue by StylianosGakis** [coil-kt/coil#863]
It would be nice if Coil could expose a composable function that could accept all the necessary parameters along with using a "slot API" to accept different composable functions to be shown while the image is on any other state other than ImagePainter.State.Success.

Something with the signature of
```
fun CoilImage(
    data: SomeDataClass,
    contentDescription: String,
    ...
    // Whatever else might fit here
    ...
    empty: @Composable BoxScope.() -> Unit,
    loading: @Composable BoxScope.() -> Unit,
    error: @Composable BoxScope.() -> Unit,
)
```
##
I have been trying to make something like that happen myself with the composable looking like this

```
@Composable
fun CoilImage(
    data: String,
    contentDescription: String,
    contentScale: ContentScale,
    loading: @Composable BoxScope.() -> Unit,
    error: @Composable BoxScope.() -> Unit,
    modifier: Modifier = Modifier
) {
    val painter = rememberImagePainter(
        data = data,
        onExecute = { _, _ -> true },
        builder = {
            size(SizeResolver(OriginalSize)) // Take a note of this line
        }
    )

    Box(modifier = modifier) {
        when (painter.state) {
            ImagePainter.State.Empty -> {
                loading()
            }
            is ImagePainter.State.Loading -> {
                loading()
            }
            is ImagePainter.State.Success -> {
                Image(
                    painter = painter,
                    contentScale = contentScale,
                    contentDescription = contentDescription,
                    modifier = Modifier.fillMaxSize()
                )
            }
            is ImagePainter.State.Error -> {
                error()
            }
        }
    }
}
```

Initially I thought that adding `onExecute = { _, _ -> true }` would execute the image request regardless of any other conditions. However, without explicitly adding the line `builder = { size(SizeResolver(OriginalSize)) }` the image would never start loading and would stay in the `ImagePainter.State.Success` state. This happened because it hit [this](https://github.com/coil-kt/coil/blob/0d117b68d5295acfc8136fa54161ab3e57f22df2/coil-compose-base/src/main/java/coil/compose/ImagePainter.kt#L181) line, "short-circuited" as you comment, and never actually executed the image request

The point that I am trying to make is that it is non obvious how to achieve this, and I believe it would make for a very reasonable composable function for the Coil library to expose to end users without needing to delve into how coil works on the inside. In fact I have no idea what manually passing the SizeResolved does and if it would break in some case, it just seems to work for me so far.

**Comment by colinrtwhite** [comment]
I think this is probably a good candidate for an external library ([looks like there already is one](https://github.com/skydoves/landscapist). `coil-compose`'s main goal is to expose a `Painter` that can be used to draw the `ImageRequest`. It's a small wrapper around `imageLoader.execute(request)` with some extra Compose support to make `ImageRequest.crossfade` work and cancel the request if it's detached from the current composition. By keeping this simple it allows users to set completely custom logic based on the `ImagePainter`'s state. Adding `@Composable BoxScope.() -> Unit` params for each state only saves a couple lines by avoiding the `when` statement.

I'd recommend avoiding `size(SizeResolver(OriginalSize))` since you're potentially decoding the image at a much larger size than is displayed on screen (which takes extra time, memory, and CPU). Ideally `ImagePainter` would be able to figure out the canvas dimensions in all cases, but it's not possible to display an image without specifying the size due to [a compose design decision](https://issuetracker.google.com/186012457).

**Comment by StylianosGakis** [comment]
Absolutely, makes sense. Thanks for helping out with the `SizeResolver(OriginalSize)` too!
