### ISSUE TITLE
ImageView dimensions are incorrect in ConstraintLayout

### ISSUE THREAD

**Issue by StephaneBg** [coil-kt/coil#95]
**Describe the bug**
When dimensions of ImageView are computed in ConstraintLayout with a constraint width percent, the size of the image is incorrect.

**To Reproduce**
Project is available. Search for ImageView with cover id.
https://github.com/damienLh/entract-cinema-android/blob/coil/app/src/main/res/layout/fragment_details.xml
https://github.com/damienLh/entract-cinema-android/blob/coil/app/src/main/kotlin/com/cinema/entract/app/ui/details/DetailsFragment.kt

**Expected behavior**
ImageView dimensions set to correct width percent constraint. In this example third of the screen width.

**Logs/Screenshots**
Current behaviour:
![Screenshot_1568215876](https://user-images.githubusercontent.com/1014339/64711529-08505a00-d4ba-11e9-876a-9a9e409e162c.png)

Expected behaviour (Glide):
![Screenshot_1568220983](https://user-images.githubusercontent.com/1014339/64718232-186e3680-d4c6-11e9-8717-7bee21d08d8c.png)

**Library version**
0.7.0

**Comment by RenatoViana01** [comment]
Can I pick this up?

**Comment by colinrtwhite** [comment]
Took a look at your sample project. This is occurring because the image (185x251) is being loaded in at a smaller size than the `ImageView` (271x406 on an xxhdpi device). Coil does this as an optimization since the image is already loaded in at max detail at its original size. However, I understand this might not be desired behaviour in all situations so I'm looking into adding an opt out for this optimization in a future release. Tracking this issue in #76.
